use_frameworks!

target 'Swiftcraft_Example' do
  pod 'Swiftcraft', :path => '../'

  pod 'SwiftSockets', '~> 0.22'
end

target 'Swiftcraft_Tests' do
  pod 'Swiftcraft', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 4.0'

  pod 'SwiftSockets', '~> 0.22'
end
